# Generated by Django 6.0.5 on 2026-07-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_phone_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinomial',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
