# Generated by Django 6.0.5 on 2026-10-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_testinomial_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_items',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub repository URL (optional — hides the Code button when empty)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project_items',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'Delivered'), ('ONGOING', 'Ongoing'), ('REFINING', 'Refining'), ('LIVE', 'Live')], default='DELIVERED', max_length=20),
        ),
    ]
